spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ACTUAL_DRGHT?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  config:
    import: application-private.yml

logging:
  file: # ?? ?? ?? ??
    name: /logs/app.log
    path: /logs
  level: # ?? ?? ??
    root: INFO
    com.yourcompany: DEBUG
    org.springframework: WARN
  logback:
    rollingpolicy: # ?? ?? ?? ??
      file-name-pattern: /logs/app-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 300MB

file:
  dir: /Users/icuh/Desktop/file_upload_test